name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Python Syntax
        run: python -m py_compile src/app/main.py

      - name: Lint dengan flake8 (keras)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Jalankan test dengan coverage
        run: |
          coverage run -m pytest src/tests/
          coverage xml

      - name: ⬆ Upload coverage report (opsional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.organization=Arwwwnbl09
            -Dsonar.projectKey=Arwwwnbl09_CICD-MKPL-Kelompok6-SE0602
            -Dsonar.sources=src/app
            -Dsonar.tests=src/tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sourceEncoding=UTF-8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
